name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
  
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14, 1.15] ## Will create 2 jobs: check-application:1.14  check-application:1.15
    steps:
      - uses: actions/checkout@v2 # Action that downloads this github repository
      - uses: actions/setup-go@v2 # Action that install go on the machine
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go