name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
  
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14, 1.15] ## Will create 2 jobs: check-application:1.14  check-application:1.15
    steps:
      - uses: actions/checkout@v2 # Action that downloads this github repository
      - uses: actions/setup-go@v2 # Action that install go on the machine
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go

      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v2 # Action to allow docker on the machine
      
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2 # Action to allow build the image to multiple architectures

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: vitor96k/full_cycle_go:latest