name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Action that downloads this github repository
      - uses: actions/setup-go@v2 # Action that install go on the machine
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go